// Mocks generated by Mockito 5.4.6 from annotations
// in financas_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:financas_app/core/errors/failures.dart' as _i7;
import 'package:financas_app/features/auth/data/datasources/auth_local_datasource.dart'
    as _i11;
import 'package:financas_app/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i10;
import 'package:financas_app/features/auth/data/models/user_model.dart' as _i2;
import 'package:financas_app/features/auth/domain/entities/user.dart' as _i9;
import 'package:financas_app/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:fpdart/fpdart.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> register({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i9.User>> verifyCode({
    required String? email,
    required String? code,
    required String? deviceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [], {
              #email: email,
              #code: code,
              #deviceName: deviceName,
            }),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, _i9.User>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i9.User>>(
                this,
                Invocation.method(#verifyCode, [], {
                  #email: email,
                  #code: code,
                  #deviceName: deviceName,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i9.User>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> resendCode({
    required String? email,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resendCode, [], {#email: email, #type: type}),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#resendCode, [], {
                  #email: email,
                  #type: type,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i9.User>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, _i9.User>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i9.User>>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i9.User>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i10.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> register(String? name, String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, email, password]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserModel> verifyCode(
    String? email,
    String? code,
    String? deviceName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [email, code, deviceName]),
            returnValue: _i5.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#verifyCode, [email, code, deviceName]),
              ),
            ),
          )
          as _i5.Future<_i2.UserModel>);

  @override
  _i5.Future<void> resendCode(String? email, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#resendCode, [email, type]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserModel> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i5.Future<_i2.UserModel>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i11.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SharedPreferences get prefs =>
      (super.noSuchMethod(
            Invocation.getter(#prefs),
            returnValue: _FakeSharedPreferences_1(
              this,
              Invocation.getter(#prefs),
            ),
          )
          as _i3.SharedPreferences);

  @override
  _i5.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
