// Mocks generated by Mockito 5.4.6 from annotations
// in financas_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dio/dio.dart' as _i8;
import 'package:financas_app/core/errors/failures.dart' as _i11;
import 'package:financas_app/features/auth/data/datasources/auth_local_datasource.dart'
    as _i15;
import 'package:financas_app/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i14;
import 'package:financas_app/features/auth/data/models/user_model.dart' as _i2;
import 'package:financas_app/features/auth/domain/entities/user.dart' as _i13;
import 'package:financas_app/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:financas_app/features/auth/domain/usecases/get_profile_usecase.dart'
    as _i21;
import 'package:financas_app/features/auth/domain/usecases/login_usecase.dart'
    as _i16;
import 'package:financas_app/features/auth/domain/usecases/logout_usecase.dart'
    as _i20;
import 'package:financas_app/features/auth/domain/usecases/register_usecase.dart'
    as _i17;
import 'package:financas_app/features/auth/domain/usecases/resend_code_usecase.dart'
    as _i19;
import 'package:financas_app/features/auth/domain/usecases/verify_code_usecase.dart'
    as _i18;
import 'package:financas_app/features/categories/data/datasources/category_remote_datasource.dart'
    as _i27;
import 'package:financas_app/features/categories/data/models/category_model.dart'
    as _i6;
import 'package:financas_app/features/categories/domain/entities/category.dart'
    as _i26;
import 'package:financas_app/features/categories/domain/repositories/category_repository.dart'
    as _i25;
import 'package:financas_app/features/dashboard/data/datasources/dashboard_remote_datasource.dart'
    as _i24;
import 'package:financas_app/features/dashboard/data/models/dashboard_summary_model.dart'
    as _i5;
import 'package:financas_app/features/dashboard/domain/entities/dashboard_summary.dart'
    as _i23;
import 'package:financas_app/features/dashboard/domain/repositories/dashboard_repository.dart'
    as _i22;
import 'package:financas_app/features/transactions/data/datasources/transaction_remote_datasource.dart'
    as _i30;
import 'package:financas_app/features/transactions/data/models/transaction_model.dart'
    as _i7;
import 'package:financas_app/features/transactions/domain/entities/transaction.dart'
    as _i29;
import 'package:financas_app/features/transactions/domain/repositories/transaction_repository.dart'
    as _i28;
import 'package:fpdart/fpdart.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_2 extends _i1.SmartFake
    implements _i4.AuthRepository {
  _FakeAuthRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardSummaryModel_3 extends _i1.SmartFake
    implements _i5.DashboardSummaryModel {
  _FakeDashboardSummaryModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryModel_4 extends _i1.SmartFake implements _i6.CategoryModel {
  _FakeCategoryModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionModel_5 extends _i1.SmartFake
    implements _i7.TransactionModel {
  _FakeTransactionModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_6 extends _i1.SmartFake implements _i8.BaseOptions {
  _FakeBaseOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_7 extends _i1.SmartFake implements _i8.Interceptors {
  _FakeInterceptors_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_8 extends _i1.SmartFake
    implements _i8.HttpClientAdapter {
  _FakeHttpClientAdapter_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_9 extends _i1.SmartFake implements _i8.Transformer {
  _FakeTransformer_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_10<T1> extends _i1.SmartFake implements _i8.Response<T1> {
  _FakeResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_11 extends _i1.SmartFake implements _i8.Dio {
  _FakeDio_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> register({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i13.User>> verifyCode({
    required String? email,
    required String? code,
    required String? deviceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [], {
              #email: email,
              #code: code,
              #deviceName: deviceName,
            }),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, _i13.User>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, _i13.User>>(
                this,
                Invocation.method(#verifyCode, [], {
                  #email: email,
                  #code: code,
                  #deviceName: deviceName,
                }),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i13.User>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> resendCode({
    required String? email,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resendCode, [], {#email: email, #type: type}),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#resendCode, [], {
                  #email: email,
                  #type: type,
                }),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i13.User>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, _i13.User>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, _i13.User>>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i13.User>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i14.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> register(String? name, String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, email, password]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.UserModel> verifyCode(
    String? email,
    String? code,
    String? deviceName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [email, code, deviceName]),
            returnValue: _i9.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#verifyCode, [email, code, deviceName]),
              ),
            ),
          )
          as _i9.Future<_i2.UserModel>);

  @override
  _i9.Future<void> resendCode(String? email, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#resendCode, [email, type]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.UserModel> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i9.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i9.Future<_i2.UserModel>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i15.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SharedPreferences get prefs =>
      (super.noSuchMethod(
            Invocation.getter(#prefs),
            returnValue: _FakeSharedPreferences_1(
              this,
              Invocation.getter(#prefs),
            ),
          )
          as _i3.SharedPreferences);

  @override
  _i9.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i16.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i17.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> call({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#call, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);
}

/// A class which mocks [VerifyCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyCodeUseCase extends _i1.Mock implements _i18.VerifyCodeUseCase {
  MockVerifyCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i13.User>> call({
    required String? email,
    required String? code,
    required String? deviceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #code: code,
              #deviceName: deviceName,
            }),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, _i13.User>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, _i13.User>>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #code: code,
                  #deviceName: deviceName,
                }),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i13.User>>);
}

/// A class which mocks [ResendCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResendCodeUseCase extends _i1.Mock implements _i19.ResendCodeUseCase {
  MockResendCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> call({
    required String? email,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #type: type}),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#call, [], {#email: email, #type: type}),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i20.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i21.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.AuthRepository);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i13.User>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, _i13.User>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, _i13.User>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i13.User>>);
}

/// A class which mocks [DashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRepository extends _i1.Mock
    implements _i22.DashboardRepository {
  MockDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i23.DashboardSummary>> getSummary({
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSummary, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue:
                _i9.Future<
                  _i10.Either<_i11.Failure, _i23.DashboardSummary>
                >.value(
                  _i12.dummyValue<
                    _i10.Either<_i11.Failure, _i23.DashboardSummary>
                  >(
                    this,
                    Invocation.method(#getSummary, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i23.DashboardSummary>>);
}

/// A class which mocks [DashboardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRemoteDataSource extends _i1.Mock
    implements _i24.DashboardRemoteDataSource {
  MockDashboardRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.DashboardSummaryModel> getSummary({
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSummary, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i9.Future<_i5.DashboardSummaryModel>.value(
              _FakeDashboardSummaryModel_3(
                this,
                Invocation.method(#getSummary, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i9.Future<_i5.DashboardSummaryModel>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i25.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i10.Either<_i11.Failure, List<_i26.Category>>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue:
                _i9.Future<
                  _i10.Either<_i11.Failure, List<_i26.Category>>
                >.value(
                  _i12.dummyValue<
                    _i10.Either<_i11.Failure, List<_i26.Category>>
                  >(this, Invocation.method(#getAll, [])),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, List<_i26.Category>>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i26.Category>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i26.Category>>.value(
                  _i12.dummyValue<_i10.Either<_i11.Failure, _i26.Category>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i26.Category>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i26.Category>> create({
    required String? name,
    required String? icon,
    required String? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #name: name,
              #icon: icon,
              #color: color,
            }),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i26.Category>>.value(
                  _i12.dummyValue<_i10.Either<_i11.Failure, _i26.Category>>(
                    this,
                    Invocation.method(#create, [], {
                      #name: name,
                      #icon: icon,
                      #color: color,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i26.Category>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i26.Category>> update({
    required String? id,
    required String? name,
    required String? icon,
    required String? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #id: id,
              #name: name,
              #icon: icon,
              #color: color,
            }),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i26.Category>>.value(
                  _i12.dummyValue<_i10.Either<_i11.Failure, _i26.Category>>(
                    this,
                    Invocation.method(#update, [], {
                      #id: id,
                      #name: name,
                      #icon: icon,
                      #color: color,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i26.Category>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);
}

/// A class which mocks [CategoryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRemoteDataSource extends _i1.Mock
    implements _i27.CategoryRemoteDataSource {
  MockCategoryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i6.CategoryModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i9.Future<List<_i6.CategoryModel>>.value(
              <_i6.CategoryModel>[],
            ),
          )
          as _i9.Future<List<_i6.CategoryModel>>);

  @override
  _i9.Future<_i6.CategoryModel> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i6.CategoryModel>.value(
              _FakeCategoryModel_4(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i9.Future<_i6.CategoryModel>);

  @override
  _i9.Future<_i6.CategoryModel> create({
    required String? name,
    required String? icon,
    required String? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #name: name,
              #icon: icon,
              #color: color,
            }),
            returnValue: _i9.Future<_i6.CategoryModel>.value(
              _FakeCategoryModel_4(
                this,
                Invocation.method(#create, [], {
                  #name: name,
                  #icon: icon,
                  #color: color,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.CategoryModel>);

  @override
  _i9.Future<_i6.CategoryModel> update({
    required String? id,
    required String? name,
    required String? icon,
    required String? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #id: id,
              #name: name,
              #icon: icon,
              #color: color,
            }),
            returnValue: _i9.Future<_i6.CategoryModel>.value(
              _FakeCategoryModel_4(
                this,
                Invocation.method(#update, [], {
                  #id: id,
                  #name: name,
                  #icon: icon,
                  #color: color,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.CategoryModel>);

  @override
  _i9.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i28.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i10.Either<_i11.Failure, List<_i29.Transaction>>> getAll({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue:
                _i9.Future<
                  _i10.Either<_i11.Failure, List<_i29.Transaction>>
                >.value(
                  _i12.dummyValue<
                    _i10.Either<_i11.Failure, List<_i29.Transaction>>
                  >(
                    this,
                    Invocation.method(#getAll, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, List<_i29.Transaction>>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>>.value(
                  _i12.dummyValue<_i10.Either<_i11.Failure, _i29.Transaction>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>> create(
    _i29.Transaction? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [transaction]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>>.value(
                  _i12.dummyValue<_i10.Either<_i11.Failure, _i29.Transaction>>(
                    this,
                    Invocation.method(#create, [transaction]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>> update(
    _i29.Transaction? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [transaction]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>>.value(
                  _i12.dummyValue<_i10.Either<_i11.Failure, _i29.Transaction>>(
                    this,
                    Invocation.method(#update, [transaction]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i29.Transaction>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);

  @override
  _i9.Future<_i10.Either<_i11.Failure, double>> getBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getBalance, []),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, double>>.value(
              _i12.dummyValue<_i10.Either<_i11.Failure, double>>(
                this,
                Invocation.method(#getBalance, []),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, double>>);
}

/// A class which mocks [TransactionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRemoteDataSource extends _i1.Mock
    implements _i30.TransactionRemoteDataSource {
  MockTransactionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i7.TransactionModel>> getAll({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i9.Future<List<_i7.TransactionModel>>.value(
              <_i7.TransactionModel>[],
            ),
          )
          as _i9.Future<List<_i7.TransactionModel>>);

  @override
  _i9.Future<_i7.TransactionModel> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i7.TransactionModel>.value(
              _FakeTransactionModel_5(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i9.Future<_i7.TransactionModel>);

  @override
  _i9.Future<_i7.TransactionModel> create(_i7.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#create, [transaction]),
            returnValue: _i9.Future<_i7.TransactionModel>.value(
              _FakeTransactionModel_5(
                this,
                Invocation.method(#create, [transaction]),
              ),
            ),
          )
          as _i9.Future<_i7.TransactionModel>);

  @override
  _i9.Future<_i7.TransactionModel> update(_i7.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#update, [transaction]),
            returnValue: _i9.Future<_i7.TransactionModel>.value(
              _FakeTransactionModel_5(
                this,
                Invocation.method(#update, [transaction]),
              ),
            ),
          )
          as _i9.Future<_i7.TransactionModel>);

  @override
  _i9.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i8.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_6(this, Invocation.getter(#options)),
          )
          as _i8.BaseOptions);

  @override
  _i8.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_7(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i8.Interceptors);

  @override
  _i8.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_8(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i8.HttpClientAdapter);

  @override
  _i8.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_9(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i8.Transformer);

  @override
  set options(_i8.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i8.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i8.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i8.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i8.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i8.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i8.FileAccessMode? fileAccessMode = _i8.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i8.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i9.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_10<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<dynamic>>);

  @override
  _i9.Future<_i8.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i8.ProgressCallback? onReceiveProgress,
    _i8.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i8.FileAccessMode? fileAccessMode = _i8.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i8.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i9.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_10<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<dynamic>>);

  @override
  _i9.Future<_i8.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.CancelToken? cancelToken,
    _i8.Options? options,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i8.CancelToken? cancelToken,
    _i8.Options? options,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i9.Future<_i8.Response<T>> fetch<T>(_i8.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i9.Future<_i8.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i9.Future<_i8.Response<T>>);

  @override
  _i8.Dio clone({
    _i8.BaseOptions? options,
    _i8.Interceptors? interceptors,
    _i8.HttpClientAdapter? httpClientAdapter,
    _i8.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_11(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i8.Dio);
}
